
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432
  user: root
  password: root

development:
  <<: *default
  database: nosso_amigo_secreto_development

test:
  <<: *default
  database: nosso_amigo_secreto_test

production:
  <<: *default
  database: nosso_amigo_secreto_production