default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: 127.0.0.1
  port: 5432
  user: root
  password: root


development:
  <<: *default
  database: V2OneBitExchange_development


test:
  <<: *default
  database: V2OneBitExchange_test
 

production:
  <<: *default
  database: V2OneBitExchange_production
  username: OneBitExchange
  password: <%= ENV['EXCHANGE_DATABASE_PASSWORD'] %>