
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: root
  user: root
  port: 5432
  host: 127.0.0.1

development:
  <<: *default
  database: onebitchat_development

test:
  <<: *default
  database: onebitchat_exchance_test

production:
  <<: *default
  database: onebitchat_exchance_production